### ISSUE TITLE
Thanos  配置跳过安全验证访问 Minio 对象存储

### ISSUE THREAD

**Issue by xkfen** [erdong/erdong.github.io#4]
config.yaml
`type: S3
config:
   bucket: "thanos"
   endpoint: "10.10.xx.xx:7480"
   region: ""
   access_key: "xxx"
   insecure: false
   signature_version2: false
   encrypt_sse: false
   secret_key: "xxx"
   put_user_metadata: {}
   http_config:
       idle_conn_timeout: 90s
       response_header_timeout: 2m
       insecure_skip_verify: true
   trace:
       enable: false
   part_size: 134217728
`

报错如下：
level=info ts=2019-12-30T11:46:41.235173686Z caller=http.go:78 service=http/server component=store msg="internal server shutdown" err="bucket store initial sync: sync block: iter: Get https://10.10.xx.xx:7480/thanos/?location=: http: server gave HTTP response to HTTPS client"

**Comment by erdong** [comment]
配置文件看起来没什么问题，`    insecure_skip_verify: true` 这个参数配置是跳过 https 的验证。

我使用了一个自签的证书，在浏览器信任证书以后是可以直接访问的Minio 的，配置文件里写的是我自己自签的域名，并且在本地 host 文件做了映射的。

1、在浏览器访问一下：https://10.10.xx.xx:7480 看看是否可以正常访问。
2、或者在配置文件里 endpoint 配置成 https://10.10.xx.xx:7480 。

**Comment by xkfen** [comment]
> 配置文件看起来没什么问题，` insecure_skip_verify: true` 这个参数配置是跳过 https 的验证。
> 
> 我使用了一个自签的证书，在浏览器信任证书以后是可以直接访问的Minio 的，配置文件里写的是我自己自签的域名，并且在本地 host 文件做了映射的。
> 
> 1、在浏览器访问一下：https://10.10.xx.xx:7480 看看是否可以正常访问。
> 2、或者在配置文件里 endpoint 配置成 https://10.10.xx.xx:7480 。

多谢大佬解答。我的问题解决了，不仅要设置insecure_skip_verify: true (insecure_skip_verify: true 只是为了跳过安全验证), 还要设置insecure为true，insecure:true的意思是用http替换https(to switch to plain insecure HTTP instead of HTTPS)

**Comment by erdong** [comment]
哦，解决了就好。我总结一下。
## 1、minio 提供了一个默认的 HTTP 访问
Thanos 需要设置两个参数
```
insecure:true
insecure_skip_verify: true
```
## 2、Minio 使用自签的证书提供了一个不受信任的 HTTPS 访问
Thanos 需要设置
```
insecure_skip_verify: true
```
## 3、Minio 使用权威机构颁发的证书提供了一个受信任的 HTTPS 访问
Thanos 不需要相关跳过认证的配置。

# 参数解释
insecure:true   是用http替换https(to switch to plain insecure HTTP instead of HTTPS
insecure_skip_verify: true   只是为了跳过安全验证

**Comment by erdong** [comment]
问题已经解决，我先关了这个 Issue。
